[package]
name = "arceus"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["."]

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = "0.23"
anyhow = "1"
